ci: add token and induce formatting errors

diff --git a/.github/workflows/cypress-tests-runner.yml b/.github/workflows/cypress-tests-runner.yml
--- a/.github/workflows/cypress-tests-runner.yml
+++ b/.github/workflows/cypress-tests-runner.yml
@@ -24,13 +24,27 @@ env:
 jobs:
   formatter:
     name: Run formatter on Cypress tests and address lints
-    if: ${{ ((github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name)) }}
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
+      - name: Generate a token
+        if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
+        id: generate_token
+        uses: actions/create-github-app-token@v1
+        with:
+          app-id: ${{ secrets.HYPERSWITCH_BOT_APP_ID }}
+          private-key: ${{ secrets.HYPERSWITCH_BOT_APP_PRIVATE_KEY }}
+
+      - name: Checkout repository with token
+        if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.head_ref || github.ref }}
+          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.ref }}
+          token: ${{ steps.generate_token.outputs.token }}
+
+      - name: Checkout repository for fork
+        if: ${{ github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
+        uses: actions/checkout@v4
 
       - name: Install Node.js
         if: ${{ env.RUN_TESTS == 'true' }}
@@ -43,6 +57,14 @@ jobs:
         if: ${{ env.RUN_TESTS == 'true' }}
         run: |
           npm ci --prefix ./cypress-tests
+
+      - name: Check formatting for forked pull requests
+        if: ${{ github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
+        shell: bash
+        run: |
+          # Checks return exit code 1 if failed and hence we use `|| true` to avoid failing the check
+          npm run format:check --prefix cypress-tests || true
+          npm run lint --prefix cypress-tests || true
 
       - name: Check formatting
         if: ${{ env.RUN_TESTS == 'true' }}
