Add retries to failed connectors
Added to address connectors like Globalpay showing inconsistencies

diff --git a/.github/workflows/postman-collection-runner.yml b/.github/workflows/postman-collection-runner.yml
--- a/.github/workflows/postman-collection-runner.yml
+++ b/.github/workflows/postman-collection-runner.yml
@@ -132,18 +132,54 @@ jobs:
           GPAY_CERTIFICATE_KEYS: ${{ secrets.STRIPE_GPAY_CERTIFICATE_KEYS }}
         shell: bash
         run: |
+          # Declare variables
           RED='\033[0;31m'
           RESET='\033[0m'
-          failed_connectors=()
+          MAX_RETRIES=3
+          FAILED_CONNECTORS=()
 
+          # Runner function
+          run_connector() {
+            local connector_name="$1"
+            if cargo run --bin test_utils -- --connector_name="$connector_name" --base_url="$BASE_URL" --admin_api_key="$ADMIN_API_KEY"; then
+              echo "Connector $connector_name executed successfully."
+              return 0
+            else
+              return 1
+            fi
+          }
+
+          # Connectors are parsed and runner is called for each connector
           for i in $(echo "$CONNECTORS" | tr "," "\n"); do
-            if ! cargo run --bin test_utils -- --connector_name="$i" --base_url="$BASE_URL" --admin_api_key="$ADMIN_API_KEY"; then
-              failed_connectors+=("$i")
+            if ! run_connector "$i"; then
+              FAILED_CONNECTORS+=("$i")
             fi
           done
 
-          if [ ${#failed_connectors[@]} -gt 0 ]; then
+          # Retry failed connectors by calling runner function with max retries set to 3
+          if [ ${#FAILED_CONNECTORS[@]} -gt 0 ]; then
             echo -e "${RED}One or more connectors failed to run:${RESET}"
-            printf '%s\n' "${failed_connectors[@]}"
-            exit 1
+            printf '%s\n' "${FAILED_CONNECTORS[@]}"
+
+            echo "Retrying failed connectors..."
+            RETRIES=0
+            while [ $RETRIES -lt $MAX_RETRIES ] && [ ${#FAILED_CONNECTORS[@]} -gt 0 ]; do
+              new_failed_connectors=()
+              for i in "${FAILED_CONNECTORS[@]}"; do
+                if run_connector "$i"; then
+                  continue  # Skip processing successful connectors during the retry loop
+                else
+                  new_failed_connectors+=("$i")
+                fi
+              done
+              FAILED_CONNECTORS=("${new_failed_connectors[@]}")
+              RETRIES=$((RETRIES + 1))
+            done
+
+            # If any connectors still failed to run after retries, exit with error
+            if [ ${#FAILED_CONNECTORS[@]} -gt 0 ]; then
+              echo -e "${RED}One or more connectors still failed to run after retries:${RESET}"
+              printf '%s\n' "${FAILED_CONNECTORS[@]}"
+              exit 1
+            fi
           fi
